'use client';
import Link from 'next/link';import { useState } from 'react';import { motion } from 'framer-motion';import { ArrowRight, Check, ChevronDown, Play, X } from 'lucide-react';import { faqs, features, industries, nav, posts } from '@/lib/content';
const fade={initial:{opacity:0,y:28,filter:'blur(8px)'},whileInView:{opacity:1,y:0,filter:'blur(0)'},viewport:{once:true,margin:'-80px'},transition:{duration:.7}};
export function Navbar(){const [open,setOpen]=useState(false);return <><header className="fixed inset-x-0 top-0 z-50 px-4 py-4"><nav className="glass mx-auto flex max-w-6xl items-center justify-between rounded-full px-5 py-3"><Link href="/" className="text-lg font-black tracking-tight">Aera</Link><div className="hidden gap-7 md:flex">{nav.map(n=><Link key={n} href={`/${n.toLowerCase()}`} className="text-sm font-semibold text-slate-600 hover:text-aera-blue">{n}</Link>)}</div><button onClick={()=>setOpen(true)} className="btn btn-primary shine">Book a Demo</button></nav></header>{open&&<DemoModal close={()=>setOpen(false)}/>}</>}
export function DemoModal({close}:{close:()=>void}){return <div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/45 p-4 backdrop-blur"><motion.div initial={{scale:.94,opacity:0}} animate={{scale:1,opacity:1}} className="card max-w-xl p-6"><div className="flex justify-between"><div><p className="eyebrow">Request demo</p><h2 className="mt-2 text-3xl font-black tracking-tight">See Aera in motion.</h2></div><button onClick={close}><X/></button></div><form className="mt-6 grid gap-3"><input className="rounded-2xl border p-4" placeholder="Work email"/><input className="rounded-2xl border p-4" placeholder="Business name"/><input className="rounded-2xl border p-4" placeholder="Phone number"/><button className="btn btn-primary mt-2">Book my demo <ArrowRight className="ml-2 size-4"/></button></form></motion.div></div>}
export function Hero(){return <section className="relative overflow-hidden bg-grid px-4 pb-24 pt-36"><div className="absolute inset-x-0 top-0 h-80 bg-gradient-to-b from-blue-100/80 to-transparent"/><div className="container relative grid items-center gap-12 lg:grid-cols-[.95fr_1.05fr]"><motion.div {...fade}><p className="eyebrow">Appointments without friction</p><h1 className="mt-5 text-[clamp(4rem,9vw,8.6rem)] font-black leading-[.84] tracking-[-.08em]">Booking made effortless.</h1><p className="lead mt-7 max-w-xl">Aera helps customers book in less than one minute using only their phone number, while your team manages services, professionals, schedules, clients, and appointments from one beautifully simple system.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/contact" className="btn btn-primary shine">Book a Demo <ArrowRight className="ml-2 size-4"/></a><button className="btn btn-secondary"><Play className="mr-2 size-4"/> Watch Demo</button></div></motion.div><ProductMockup/></div></section>}
export function ProductMockup(){return <motion.div {...fade} className="float card relative p-4 shadow-glow"><div className="rounded-[1.5rem] bg-slate-950 p-5 text-white"><div className="mb-5 flex items-center justify-between"><b>Today</b><span className="rounded-full bg-blue-500 px-3 py-1 text-xs">12 booked</span></div>{['09:00 Haircut','10:00 Consultation','11:30 Treatment','13:00 Follow-up'].map((x,i)=><div key={x} className="mb-3 rounded-2xl bg-white/10 p-4" style={{marginLeft:i%2?36:0}}><p className="font-bold">{x}</p><p className="text-sm text-slate-300">OTP verified · no account needed</p></div>)}</div></motion.div>}
export function SectionTitle({kicker,title,text}:{kicker:string,title:string,text:string}){return <motion.div {...fade} className="mx-auto mb-14 max-w-3xl text-center"><p className="eyebrow">{kicker}</p><h2 className="h2 mt-3">{title}</h2><p className="lead mt-5">{text}</p></motion.div>}
export function FeatureGrid(){return <div className="container grid gap-4 md:grid-cols-2 lg:grid-cols-4">{features.map((f,i)=><motion.div {...fade} transition={{duration:.6,delay:i*.04}} key={f.title} className="card p-6 transition hover:-translate-y-1 hover:shadow-glow"><f.icon className="mb-8 size-7 text-aera-blue"/><h3 className="text-xl font-black">{f.title}</h3><p className="mt-3 text-slate-500">{f.text}</p></motion.div>)}</div>}
export function HomeSections(){return <><section className="section"><SectionTitle kicker="Problem" title="Booking is still too much work." text="Accounts, passwords, phone calls, repeated questions, and unclear availability create drop-off before the appointment exists."/><div className="container grid gap-4 md:grid-cols-3">{['Missed calls become missed revenue.','Long forms make customers quit.','Manual calendars create costly mistakes.'].map(x=><div className="card p-8 text-2xl font-black" key={x}>{x}</div>)}</div></section><section className="section bg-aera-soft"><SectionTitle kicker="Solution" title="One minute from intent to appointment." text="Aera strips booking down to the decisions that matter: service, professional, time, phone verification, done."/><Timeline/></section><section className="section"><SectionTitle kicker="Platform" title="Everything the business needs. Nothing the customer does not." text="A complete appointment management platform designed around speed, trust, and operational clarity."/><FeatureGrid/></section><Industries/><Testimonials/><Comparison/><Stats/><PricingPreview/><FAQ/><FinalCTA/></>}
export function Timeline(){return <div className="container grid gap-4 md:grid-cols-4">{['Choose service','Pick professional','Verify by OTP','Arrive informed'].map((x,i)=><motion.div {...fade} key={x} className="card p-7"><span className="text-5xl font-black text-blue-100">0{i+1}</span><h3 className="mt-8 text-xl font-black">{x}</h3><p className="mt-2 text-slate-500">Designed to feel obvious, fast, and calm on any device.</p></motion.div>)}</div>}
export function Industries(){return <section className="section"><SectionTitle kicker="Industries" title="Built for appointment-led businesses." text="Aera adapts to high-touch teams where time, trust, and professional presentation matter."/><div className="container grid gap-4 md:grid-cols-4">{industries.map(x=><Link href="/industries" key={x} className="card p-6 font-black hover:text-aera-blue">{x}</Link>)}</div></section>}
export function Testimonials(){return <section className="section bg-slate-950 text-white"><SectionTitle kicker="Proof" title="Feels premium before the first visit." text="Teams choose Aera because it makes their business easier to run and easier to trust."/><div className="container grid gap-4 md:grid-cols-3">{['Our clients stopped asking how to book. They just book.','The calendar finally feels like a command center.','Aera made us look more professional overnight.'].map((q,i)=><div className="rounded-[2rem] bg-white/10 p-8" key={q}>“{q}”<p className="mt-8 text-sm text-blue-200">Founder, Studio {i+1}</p></div>)}</div></section>}
export function Comparison(){return <section className="section"><SectionTitle kicker="Comparison" title="Traditional booking vs. Aera." text="Replace friction-heavy workflows with a phone-first journey customers finish quickly."/><div className="container grid gap-4 md:grid-cols-2"><div className="card p-8 opacity-70"><h3 className="text-2xl font-black">Traditional</h3>{['Call during business hours','Create account','Wait for confirmation','Manually update staff'].map(x=><p className="mt-4" key={x}>✕ {x}</p>)}</div><div className="card border-blue-200 p-8 shadow-glow"><h3 className="text-2xl font-black text-aera-blue">Aera</h3>{['Book any time','Verify by phone','Instant clarity','Team calendar synchronized'].map(x=><p className="mt-4" key={x}><Check className="mr-2 inline size-4 text-aera-success"/> {x}</p>)}</div></div></section>}
export function Stats(){return <section className="section bg-aera-soft"><div className="container grid gap-4 text-center md:grid-cols-3">{['< 60 sec average booking','0 passwords for clients','24/7 online availability'].map(x=><div className="card p-10 text-3xl font-black" key={x}>{x}</div>)}</div></section>}
export function PricingPreview(){return <section className="section"><SectionTitle kicker="Pricing" title="Clear plans. No hidden fees." text="Start with the scheduling foundation, then scale into deeper team and reporting workflows."/><PricingCards/></section>}
export function PricingCards(){return <div className="container grid gap-4 md:grid-cols-3">{['Starter $49','Growth $99','Enterprise Custom'].map((p,i)=><div key={p} className={`card p-8 ${i==1?'border-blue-300 shadow-glow':''}`}><h3 className="text-2xl font-black">{p}</h3><p className="mt-4 text-slate-500">For modern teams that want simpler appointment management.</p><a href="/contact" className="btn btn-primary mt-8 w-full">Request demo</a></div>)}</div>}
export function FAQ(){return <section className="section bg-aera-soft"><SectionTitle kicker="FAQ" title="Questions, answered simply." text="Everything you need to know before seeing Aera in action."/><div className="container max-w-3xl">{faqs.map(([q,a])=><details className="card mb-3 p-6" key={q}><summary className="flex cursor-pointer justify-between font-black">{q}<ChevronDown/></summary><p className="mt-4 text-slate-500">{a}</p></details>)}</div></section>}
export function FinalCTA(){return <section className="section"><div className="container rounded-[3rem] bg-slate-950 p-12 text-center text-white shadow-glow"><p className="eyebrow">Ready</p><h2 className="h2 mt-3">Make booking feel effortless.</h2><a href="/contact" className="btn btn-primary mt-8">Book a Demo</a></div></section>}
export function Footer(){return <footer className="border-t px-4 py-12"><div className="container flex flex-col justify-between gap-6 md:flex-row"><b>Aera</b><p className="text-slate-500">© 2026 Aera. Appointments without friction.</p><div className="flex gap-4 text-sm"><Link href="/legal">Legal</Link><Link href="/contact">Contact</Link></div></div><CookieBanner/></footer>}
export function CookieBanner(){const [show,set]=useState(true);return show?<div className="fixed bottom-4 left-4 right-4 z-50 mx-auto max-w-xl rounded-2xl border bg-white p-4 shadow-card"><div className="flex items-center justify-between gap-4"><p className="text-sm text-slate-600">Aera uses cookies to improve performance and understand demo interest.</p><button onClick={()=>set(false)} className="btn btn-primary py-2">Accept</button></div></div>:null}
export function PageShell({children}:{children:React.ReactNode}){return <><Navbar/><main>{children}</main><Footer/></>}
export function BlogList(){return <div className="container grid gap-4 md:grid-cols-3">{posts.map(([t,c,d])=><article className="card p-7" key={t}><p className="eyebrow">{c}</p><h3 className="mt-4 text-2xl font-black">{t}</h3><p className="mt-3 text-slate-500">{d}</p></article>)}</div>}
